<?php

namespace UserBundle\Repository;

/**
 * ManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
