<?php

namespace ManagementBundle\Repository;

/**
 * AcademicYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademicYearRepository extends \Doctrine\ORM\EntityRepository
{
}
