<?php

namespace ManagementBundle\Repository;

/**
 * ReferentielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferentielRepository extends \Doctrine\ORM\EntityRepository
{
}
