<?php

namespace ManagementBundle\Repository;

/**
 * SemesterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemesterRepository extends \Doctrine\ORM\EntityRepository
{
}
